export const Genres = {
  Action: 1,
  Adventure: 2,
  Cars: 3,
  Comedy: 4,
  Dementia: 5,
  Demons: 6,
  Mystery: 7,
  Drama: 8,
  Ecchi: 9,
  Fantasy: 10,
  Game: 11,
  Hentai: 12,
  Historical: 13,
  Horror: 14,
  Kids: 15,
  Magic: 16,
  "Martial Arts": 17,
  Mecha: 18,
  Music: 19,
  Parody: 20,
  Samurai: 21,
  Romance: 22,
  School: 23,
  "Sci Fi": 24,
  Shoujo: 25,
  "Shoujo Ai": 26,
  Shounen: 27,
  "Shounen Ai": 28,
  Space: 29,
  Sports: 30,
  "Super Power": 31,
  Vampire: 32,
  Yaoi: 33,
  Yuri: 34,
  Harem: 35,
  "Slice Of Life": 36,
  Supernatural: 37,
  Military: 38,
  Police: 39,
  Psychological: 40,
};

export const ExtraAnimeGenres = {
  Thriller: 41,
  Seinen: 42,
  Josei: 43,
};

export const ExtraMangaGenres = {
  Seinen: 41,
  Josei: 42,
  Doujinshi: 43,
  "Gender Bender": 44,
  Thriller: 45,
};

export default { Genres, ExtraAnimeGenres, ExtraMangaGenres };
